spring:
  application:
    name: eureka-client-1
  output:
    ansi:
      enabled: always

server:
  port: 8061

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8061/eureka
