spring:
  application:
    name: eureka-client-1
  port: 8061
  output:
    ansi:
      enabled: always

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 5000
