spring:
  application:
    name: gateway
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: client1-route
              uri: lb://eureka-client-1
              predicates:
                - Path=/client-1/**
              filters:
                - StripPrefix=1
            - id: client2-route
              uri: lb://eureka-client-2
              predicates:
                - Path=/client-2/**
              filters:
                - StripPrefix=1

server:
  port: 8080